Admission Controller POC
scylladb/scylla-operator-autoscaler pull request #17
Opened 2021-01-14 19:45 UTC by cezarybednarz

2021-01-21 10:16 UTC, zimnx requested changes

2021-01-21 10:16 UTC, zimnx commented on Makefile
> +REPO        		?= cezarybednarz
I added repos for all these three images, you guys should have access to push images there:
https://hub.docker.com/r/scyllazimnx/scylla-operator-autoscaler-admission-controller
https://hub.docker.com/r/scyllazimnx/scylla-operator-autoscaler-recommender
https://hub.docker.com/r/scyllazimnx/scylla-operator-autoscaler-updater
Please use these here

2021-01-21 10:16 UTC, zimnx commented on Makefile
> +DOCKER_BUILDKIT        		 	:= 1
It's not used by anything

2021-01-21 10:16 UTC, zimnx commented on cmd/admission-controller/admission_controller.go
> +			webhookServer.Register("/mutate-scylla-scylladb-com-v1-scyllacluster", &webhook.Admission{Handler: &recommendationApplier{Client: mgr.GetClient(), logger: logger}})
line is too long

2021-01-21 10:16 UTC, zimnx commented on cmd/admission-controller/main.go
> +	var rootCmd = &cobra.Command{}
Let's drop `cobra` from this binary. There're no config files nor parameters so far.

2021-01-21 10:16 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +	}
```suggestion
	if err := ra.decoder.Decode(req, cluster); err != nil {
		return admission.Errored(http.StatusBadRequest, err)
	}
```

2021-01-21 10:16 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +	}
Same applies below

2021-01-21 10:16 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +	}
```suggestion
	if err = c.List(ctx, scas); err != nil {
		return fmt.Errorf("Failed to get SCAs: %s", err)
	}
```

2021-01-21 10:16 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +	}
Please create client on initialization, not on every request

2021-01-21 10:16 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +	for idx := range scas.Items {
Shouldn't this list be filetered to find SCA pointing to cluster under mutation?

2021-01-21 10:16 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +		if cluster.Spec.Datacenter.Name != dataCenterName {
This is always false

2021-01-21 10:16 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +			return dcRecs[idx].RackRecommendations
```suggestion
			return dcRecs[idx].RackRecommendations
```

2021-01-21 10:16 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +	if dcRecs == nil || len(dcRecs) == 0 {
len(nil) == 0, so you can simply check length

2021-01-21 10:16 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +			if rackRec.Name != rack.Name {
first you're searching for rack in findRack(), and then you double check if it's the rack you were looking for. Trust yourself :D

2021-01-21 10:16 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +	}
```suggestion
	if err := mutateCluster(ctx, ra.logger, cluster); err != nil {
		return admission.Errored(http.StatusInternalServerError, err)
	}
```

2021-01-21 10:16 UTC, zimnx commented on config/certmanager/certificate.yaml
> +  secretName: webhook-server-cert # this secret will not be prefixed, since it's not managed by kustomize
missing empty line

2021-01-21 10:16 UTC, zimnx commented on config/certmanager/kustomization.yaml
> +  - kustomizeconfig.yaml
missing empty line

2021-01-21 10:16 UTC, zimnx commented on config/certmanager/kustomizeconfig.yaml
> +    path: spec/dnsNames
missing empty line

2021-02-24 10:27 UTC, zimnx commented
It doesn't work, update API call is missing. Please test it first, and resolve conflicts.

2021-02-24 10:54 UTC, zimnx requested changes
Left comments inline, please add unit tests.

2021-02-24 10:54 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +	return dcRecs
nil slice and zero len slice should be treated the same, you can simply return `sca.Status.Recommendations.DataCenterRecommendations`

2021-02-24 10:54 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +	for idx := range scas.Items {
This comment is not resolved.

2021-02-24 10:54 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +			logger.Debug(ctx, "Autoscaler has 'off' scaling policy, skipping", "autoscaler", sca.ObjectMeta.Name)
```suggestion
			logger.Debug(ctx, "Autoscaler has 'off' scaling policy, skipping", "autoscaler", sca.Name)
```

2021-02-24 10:54 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +		}
It's pointless to fetch it here. You have cluster under mutation in function parameters, you can simply compare targetRef name and namespace with it without fetching.

2021-02-24 10:54 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +			logger.Debug(ctx, "SCA not pointing to cluster under mutation")
return is missing

2021-02-24 10:54 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +		if referencedCluster != cluster {
This isn't going to work, pointers nor deeper value won't be equal. You're only interested in identifier which is UID or pair of namespace and name.

2021-02-24 10:54 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +		logger.Debug(ctx, "Cluster has 'Initial' or 'Auto' scaling policy")
Why not log which one is used?

2021-02-24 10:54 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +				logger.Debug(ctx, "Could not find rack matching recommendation", "rack", rackRec.Name)
This should be logged as error, not debug.

2021-02-24 10:54 UTC, zimnx commented on cmd/admission-controller/mutatingwebhook.go
> +
Update is missing, you're modyfing rack in memory of admission controller process.

2021-03-10 12:14 UTC, zimnx reviewed
good job, some test refactorig is needed

2021-03-10 12:14 UTC, zimnx commented on cmd/admission-controller/validatingwebhook.go
> +	for idx := range scas.Items {
nit: you can use `for _, sca := range scas.Items`
same in inner loop

2021-03-10 12:14 UTC, zimnx commented on cmd/admission-controller/validatingwebhook.go
> +					break
what if it's not found?

2021-03-10 12:14 UTC, zimnx commented on cmd/admission-controller/validatingwebhook.go
> +			if !rack.Resources.Requests.Cpu().Equal(*oldRack.Resources.Requests.Cpu()) {
it has to check entire resources, not just requests.cpu.

2021-03-10 12:14 UTC, zimnx commented on cmd/admission-controller/validatingwebhook.go
> +	updaterServiceAccountUsername = "system:serviceaccount:scylla-operator-autoscaler-system:scylla-operator-autoscaler-updater-service-account"
This should be a CLI parameter with default value

2021-03-10 12:14 UTC, zimnx commented on cmd/admission-controller/validatingwebhook_test.go
> +			oldCluster: oldBasicCluster,
if it's the same, why you're using different variable? I know it's the same, but it's odd.

2021-03-10 12:14 UTC, zimnx commented on cmd/admission-controller/validatingwebhook_test.go
> +			scas:       basicScas,
what is basic? name should describe what's so special about it, wheter it's auto/off mode, whether it contains single rack node increasing recomendation etc

2021-03-10 12:14 UTC, zimnx commented on cmd/admission-controller/validatingwebhook_test.go
> +			name:       "unchanged cluster",
naming of tests could be improved to describe expected behavior. "allow empty update", "deny changing CPU limits" etc

2021-03-10 12:14 UTC, zimnx commented on config/admission-controller/admission_controller.yaml
> +            limits:
remove the limit

2021-03-10 14:56 UTC, closed without merging

2021-03-12 17:32 UTC, cezarybednarz commented on cmd/admission-controller/validatingwebhook.go
> +			if !rack.Resources.Requests.Cpu().Equal(*oldRack.Resources.Requests.Cpu()) {
I think we care only about requests.cpu because it's the only value scaled by autoscaler

2021-03-16 14:43 UTC, zimnx commented on cmd/admission-controller/validatingwebhook.go
> +			if !rack.Resources.Requests.Cpu().Equal(*oldRack.Resources.Requests.Cpu()) {
and limits.cpu (https://github.com/scylladb/scylla-operator-autoscaler/pull/19/files#diff-36d043d1b3fe2d0a248f67a2c154427e46a67dfc966a1343afaf28a3348c7c61R231)

2021-03-16 15:48 UTC, cezarybednarz commented
reopen