Admission controller POC
scylladb/scylla-operator-autoscaler pull request #22
Opened 2021-03-15 15:46 UTC by cezarybednarz

2021-03-16 14:33 UTC, zimnx commented
Why new PR was opened? This one lacks history of comments, i can't check whether you addressed them or how.

2021-03-16 15:51 UTC, cezarybednarz commented
Link to previous pull request with history of comments: https://github.com/scylladb/scylla-operator-autoscaler/pull/17

2021-03-22 15:23 UTC, zimnx requested changes
small nits

2021-03-22 15:23 UTC, zimnx commented on cmd/admission-controller/admission_controller.go
> +					ScaledResources:               []string{"cpu"},
accept as app parameter

2021-03-22 15:23 UTC, zimnx commented on pkg/admission_controller/validatingwebhook_test.go
> +			scaledResources: []string{"Memory"},
`Memory` -> `memory`

2021-03-29 09:26 UTC, zimnx reviewed
rebase is needed and one comment

2021-03-29 09:26 UTC, zimnx commented on config/default/admission_controller_webhook_patch.yaml
> +            - containerPort: 443
9443

2021-03-29 09:44 UTC, zimnx commented on config/webhook/service.yaml
> +      targetPort: webhook
`webhook-server`

2021-03-29 10:12 UTC, zimnx approved these changes

2021-03-29 10:13 UTC, merged